// Public facts approved by Negar. Update alongside the website and CV.
export const profile = `
ABOUT: Negar Honarvar Sedighian is a computer engineering graduate of Shahid Beheshti University, based in Mashhad, Iran. Her work connects deep learning with healthcare, language, and robotics.
EXPERIENCE: AI Engineer at Salamat Binesh Farda, September 2026–present, collaborating closely with dentists to develop AI models for dental assistants. Also currently AI Engineer at Amoot, Mashhad, January 2026–present: phishing detection systems and a Farsi AI assistant. Network Security Assistant at Dotin, June–October 2023: resource access management using Windows Azure and analysis of network weaknesses. Intern at Dotin School, January–June 2023: vulnerabilities, risk assessment, incident response and penetration testing.
EDUCATION: B.Sc. Computer Engineering, Shahid Beheshti University, September 2020–February 2025. GPA 17.49/20 (3.68/4); final two years 18.32/20 (3.79/4). Farzanegan 1 High School, Mashhad (SAMPAD), Mathematics diploma, September 2017–June 2020. GPA 19.95/20 (4/4). Ranked first in the SAMPAD high-school entry exam in Khorasan Razavi Province in 2017.
LANGUAGES: Advanced English CEFR C1, TOEFL iBT 108/120. Intermediate French CEFR B1, continuing study. Developing Spanish proficiency.
RESEARCH: Completed B.Sc. thesis on cascading dynamic attentive graph neural networks for cardiac MRI reconstruction, supervised by Dr. Mohsen Ebrahimi Moghaddam at the Image Processing and Distributed Systems Lab, Shahid Beheshti University. Interests include graph neural networks, accelerated MRI reconstruction, super-resolution, denoising, robotics and deep learning in finance.
PROJECTS: DAGMRNet reconstructs undersampled cardiac MRI using dynamic attentive graph learning for spatial and temporal relationships, with PromptUnet sensitivity map estimation. StockTrading_DRL combines LSTM and Proximal Policy Optimization (PPO) for stock trading; the website chart is illustrative, not measured performance. Guidance-of-a-Quadcopter-for-Object-Detection uses a Webots quadcopter controller and CNN to detect Fashion-MNIST targets and land next to a matching target; the flight video is a simulation. Enhanced-News-Classification-On-Large-Dataset classifies Farsi news with a neural network, tokenization and feature extraction. Bug-Algorithms explores robot navigation and maze mapping in Webots. TronGame uses genetic algorithms and Minimax. Repositories: https://github.com/negarhonarvar (project names above are repository names).
HONORS: Top 10 among outstanding SBU computer engineering undergraduates, 2025. National university entrance rank 321/160000, 2020. First place National Cyber Security and Cryptography Competition at Ferdowsi University of Mashhad, 2019 and 2020.
TEACHING: Teaching assistant, 2023–2025, in courses including Discrete Mathematics, Algorithms, Software Engineering, Technical English, Computer Architecture, Advanced Programming, AI, Compiler Design, Computational Intelligence, Operating Systems Laboratory, Statistics and Probability.
CONTACT: Email negarhonarvar.se@gmail.com; Telegram @negarhonarvar; GitHub https://github.com/negarhonarvar; LinkedIn https://linkedin.com/in/negar-honarvar-sedighian; CV https://negarhonarvar.github.io/files/NegarHonarvar.pdf.
`;
